# Generated by Django 4.2.2 on 2023-07-11 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={"verbose_name": "redactor", "verbose_name_plural": "redactors"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["name"]},
        ),
    ]
